name = "ouvidoria-digital"
main = "src/app.ts"
compatibility_date = "2026-01-09"

[[d1_databases]]
binding = "DB"
database_name = "ouvidoria"

[[kv_namespaces]]
binding = "KV"
id = "xxxxxx"

[vars]
JWT_SECRET = "sua_chave"
OPENAI_API_KEY = "sua_api_openai"
N8N_SECRET = "token_webhook"
